version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: springapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: devpass
      MYSQL_DATABASE: springapp
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend/demo
    container_name: springapp-backend
    ports:
      - "8080:8080"
    environment:
      JDBC_DATABASE_USERNAME: devuser
      JDBC_DATABASE_PASSWORD: devpass
      JDBC_DATABASE_URL: jdbc:mysql://mysql:3306/springapp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  db_data:
